[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=fetchai"

[tool.coverage.run]
source = ["fetchai/"]

[tool.coverage.report]
fail_under = 42
sort = "-Cover"
show_missing = true
