name: Run Python Unit Tests

on:
  push

jobs:
  release:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install .
        pip install .[dev]

    - name: Test with pytest
      run: |
        source venv/bin/activate
        pytest .
